name: actions-release
description: actions-rele
inputs:
  token:
    description: GitHub access token for GitHub CLI
    required: false
    default: ${{ github.token }}
  tag:
    description: The tag for a release.
    required: true
  overwrite-major-minor:
    description: |
      Whether to overwrite the existing major or minor tags.
      For example, when `tag` is `v1.2.0`, this action will overwrite `v1.2` and `v1`
      with the latest commit. The default value is `true`.
    required: false
    default: 'true'
  apply:
    description: Whether to apply the release.
    type: boolean
runs:
  using: composite
  steps:
    - name: git-push(1)
      shell: bash -euxo pipefail {0}
      run: |
        MINOR_TAG="${TAG%.*}"
        MAJOR_TAG="${TAG%%.*}"

        gh release list

        if [[ "${{ inputs.overwrite-major-minor }}" == "true" ]]; then
          git tag --force "$MINOR_TAG"

          if [[ "$MAJOR_TAG" != "v0" ]]; then
            git tag --force "$MAJOR_TAG"
          fi
        fi

        if [[ '${{ inputs.apply }}' == "true" ]]; then
          gh release create "$TAG" --generate-notes
          git push --force --tags
        fi

      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        TAG: ${{ inputs.tag }}
